### PR TITLE
Add initial grammar proposal from lalex

### PR DESCRIPTION
**Pull request by elmex**
I have already changed the lambda syntax from (...) to \ ... -> for now.

### CODE REVIEW

**Comment by simonorono** [comment]
Please adjust your proposal to match [this](https://github.com/protonlang/proposals/tree/master/0000-example) template. We will handle the numbering soon.

**Comment by simonorono** [comment]
According to the grammar, you have a syntax error in both of your examples :)

```
let add     = \a b -> $+ a b;
    my_sum  = $add ($add 10 20) 30; //=> 60
$print $add my_sum 30;              //stdout=> 90
```

Assignments are missing the `!`. It should be:

```
let !add     = \a b -> $+ a b;
    !my_sum  = $add ($add 10 20) 30; //=> 60
$print $add my_sum 30;               //stdout=> 90
```

**Comment by simonorono** [comment]
In the OOP example:

```
    my_account = $account_new;
in
    #$ :deposit! my_account 10;
// or:
    ##$ :deposit! 10 my_account;
// or:
    $my_account :deposit! 10;
```
1. in the grammar :deposit would be a keyword. What's the use for those? Are they not language keywords? e.g. `let`, `do`, `in`
2. What does `!` stands for at the end of `:deposit!`?

**Comment by elmex** [comment]
First, let is not an assignment, it's a binding which does not mutate the state but declares a new name.
I tried to make assignments which mutate existing bindings as explicit as possible. So I made the exclamation-mark syntax.

The ! in :deposit! is just conventional. Like (set! ...) in Scheme, to mark mutating operations.
Keywords as in languages like Clojure, where they are self-evaluating values. They are mostly
arbitrary strings which can be matched. But as keywords are not supposed to be mutable,
the compiler/interpreter can optimize them and internalize them easily.

**Comment by simonorono** [comment]
In the grammar `let` is defined with the rule `assignment`:

```
let             = "let" , { assignment ,  ";" } , "in" , expr-list ;
assignment      = "!" , identifier , "=" , expr ;
```

That's why the `!` is needed.

**Comment by elmex** [comment]
Thanks for spotting. This is why we can't have nice things :-)

**Pull request merged**
